name: Build with Zig on Windows
on:
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - "lua/"
      - "*.md"

jobs:
  build:
    permissions:
      contents: read
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6.0.1
      with:
        submodules: recursive

    - name: Install dependencies
      shell: bash
      run: |
        choco install ninja zip -y
        # Install Zig
        curl -L https://ziglang.org/download/0.15.2/zig-x86_64-windows-0.15.2.zip -o zig.zip
        7z.exe x -y zig.zip

    - name: Build luajit support mod and C++ examples
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        export PATH=$PWD/zig-x86_64-windows-0.15.2:$PATH
        ./zig.cmd

    - name: Collect Artifact
      shell: bash
      run: |
        mkdir ./artifact
        # For every directory containing a .elf file, zip it into ./artifact
        find ./.zig -name '*.elf' -execdir bash -c "zip -r \"${PWD}/artifact/\$(basename \$(realpath .)).zip\" ." \;

    - name: Upload Artifact
      uses: actions/upload-artifact@v6
      with:
        name: artifact
        path: ./artifact
