name: Build with Zig on Windows
on:
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - "lua/"
      - "*.md"

jobs:
  build:
    permissions:
      contents: read
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6.0.1
      with:
        submodules: recursive

    - name: Install dependencies
      shell: bash
      run: |
        choco install ninja
        # Install Zig
        curl -L https://ziglang.org/download/0.15.2/zig-x86_64-windows-0.15.2.zip -o zig.zip
        7z.exe x -y zig.zip

    - name: Build luajit support mod and C++ examples
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        export PATH=$PWD/zig-x86_64-windows-0.15.2:$PATH
        cmd /c ./build-zig.cmd

    - name: Collect Artifact
      if: github.event_name == 'push'
      shell: bash
      run: |
        mkdir ./artifact
        find ./mods/ -name '*.elf' -exec cp "{}" ./artifact \;
        ${{github.ref_name}}

    - name: Upload Artifact
      uses: actions/upload-artifact@v6
      if: github.event_name == 'push'
      with:
        name: artifact
        path: ./artifact
